#ifndef _ERRORS_H
#define _ERRORS_H

#define SDL_INIT_ERROR 1
#define IMG_INIT_ERROR 2
#define MIX_INIT_ERROR 3
#define MIX_OPEN_AUDIO_ERROR 4
#define MIX_ALLOCATE_CHANNELS_ERROR 5
#define SDL_CREATE_WINDOW_ERROR 6
#define SDL_CREATE_RENDER_ERROR 7
#define MIX_PLAY_MUSIC_ERROR 8
#define MIX_STOP_ERROR 9
#define MIX_FADE_OUT_ERROR 10
#define MIX_OPEN_ERROR 11
#define IMG_LOAD_TEXTURE_ERROR 12
#define SDL_QUERY_TEXTURE_ERROR 13
#define SDL_RENDER_COPY_ERROR 14
#define MULTIPLE_GAMES_ERROR 15

#endif